version: "3.2"

services:
  feature:
    image: feature
    build:
      context: .
      dockerfile: ops/docker/Dockerfile
    environment:
      FEATURE_FLAGR_URL: "http://flagr:18000"
    volumes:
      - .:/app
    depends_on:
      - flagr

  flagr:
    image: ghcr.io/openflagr/flagr
    environment:
      FLAGR_BASIC_AUTH_ENABLED: "true"
      FLAGR_BASIC_AUTH_USERNAME: flagr
      FLAGR_BASIC_AUTH_PASSWORD: flagr
      FLAGR_BASIC_AUTH_WHITELIST_PATHS: "/api/v1/health,/api/v1/evaluation"
