name: phpstan
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OSKAR-phpstan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
